<?xml version="1.0"?>
<!-- edit the .xacro file, NOT the .world file 
		run 
		rosrun xacro xacro thisfile.world..xacro > thisfile.world
		to create the world file -->
<sdf version="1.4">
  <world name="MAST demo room" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="room_width" value="10"/>
  <xacro:property name="room_length" value="15"/>
  <xacro:property name="wall_height" value="2"/>
  <xacro:property name="wall_thickness" value="0.1"/>
  <xacro:property name="floor_color" value="0.6 0.4 0.2 0.0"/>
  <xacro:property name="wall_color" value="0.0 0.0 0.1 0.0"/>
  <xacro:property name="cylinder_color" value="0.5 0.0 0.0 0.0"/>
  <xacro:property name="box_color" value="0.0 0.5 0.0 0.0"/>
    <scene>
      <ambient>0.5 0.5 0.5 1</ambient>
      <background>0.5 0.5 0.5 1</background>
      <shadows>false</shadows>
    </scene>
    <physics type="ode">
      <gravity>0 0 -9.81</gravity>
      <ode>
        <solver>
          <type>quick</type>
          <iters>10</iters>
          <sor>1.3</sor>
        </solver>
        <constraints>
          <cfm>0.0</cfm>
          <erp>0.2</erp>
          <contact_max_correcting_vel>10</contact_max_correcting_vel>
          <contact_surface_layer>0.001</contact_surface_layer>
        </constraints>
      </ode>
      <max_step_size>0.001</max_step_size>
    </physics>
    <light type="directional" name="directional_light_1">
      <pose>0 20 20 0.1 0.1 0</pose>
      <diffuse>1 1 1 1</diffuse>
      <specular>1 1 1 1</specular>
      <attenuation>
        <range>300</range>
      </attenuation>
      <direction>0.1 0.1 -1</direction>
      <cast_shadows>false</cast_shadows>
    </light>
    <!-- Ground plane -->
    <model name="ground">
      <static>true</static>
      <link name="ground_link">
        <collision name="collision">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>${room_width} ${room_length}</size>
            </plane>
          </geometry>
          <surface>
            <friction>
              <ode>
                <mu>100</mu>
                <mu2>50</mu2>
              </ode>
            </friction>
          </surface>
        </collision>
        <visual name="visual">
          <cast_shadows>false</cast_shadows>
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>${room_width} ${room_length}</size>
            </plane>
          </geometry>
          <material>
						<ambient>${floor_color}</ambient>
						<diffuse>${floor_color}</diffuse>
          </material>
        </visual>
      </link>
    </model>
    <!-- walls -->
    <model name="wall1">
      <static>true</static>
      <link name="wall1_link">
				<pose>${room_width/2} 0 ${wall_height/2} 0 0 0</pose>
        <collision name="collision">
          <geometry>
            <box>
              <size>${wall_thickness} ${room_length} ${wall_height}</size>
            </box>
          </geometry>
        </collision>
        <visual name="visual">
          <cast_shadows>true</cast_shadows>
          <geometry>
            <box>
              <size>${wall_thickness} ${room_length} ${wall_height}</size>
            </box>
          </geometry>
          <material>
						<ambient>${wall_color}</ambient>
          </material>
        </visual>
      </link>
    </model>

    <model name="wall1">
      <static>true</static>
      <link name="wall1_link">
				<pose>${room_width/2} 0 ${wall_height/2} 0 0 0</pose>
        <collision name="collision">
          <geometry>
            <box>
              <size>${wall_thickness} ${room_length} ${wall_height}</size>
            </box>
          </geometry>
        </collision>
        <visual name="visual">
          <cast_shadows>true</cast_shadows>
          <geometry>
            <box>
              <size>${wall_thickness} ${room_length} ${wall_height}</size>
            </box>
          </geometry>
          <material>
						<ambient>${wall_color}</ambient>
          </material>
        </visual>
      </link>
    </model>
    <model name="wall2">
      <static>true</static>
      <link name="wall2_link">
				<pose>${-room_width/2} 0 ${wall_height/2} 0 0 0</pose>
        <collision name="collision">
          <geometry>
            <box>
              <size>${wall_thickness} ${room_length} ${wall_height}</size>
            </box>
          </geometry>
        </collision>
        <visual name="visual">
          <cast_shadows>true</cast_shadows>
          <geometry>
            <box>
              <size>${wall_thickness} ${room_length} ${wall_height}</size>
            </box>
          </geometry>
          <material>
						<ambient>${wall_color}</ambient>
          </material>
        </visual>
      </link>
    </model>
    <model name="wall3">
      <static>true</static>
      <link name="wall3_link">
				<pose>0 ${room_length/2} ${wall_height/2} 0 0 0</pose>
        <collision name="collision">
          <geometry>
            <box>
              <size> ${room_width} ${wall_thickness} ${wall_height}</size>
            </box>
          </geometry>
        </collision>
        <visual name="visual">
          <cast_shadows>true</cast_shadows>
          <geometry>
            <box>
              <size> ${room_width} ${wall_thickness} ${wall_height}</size>
            </box>
          </geometry>
          <material>
						<ambient>${wall_color}</ambient>
          </material>
        </visual>
      </link>
    </model>
    <model name="wall4">
      <static>true</static>
      <link name="wall4_link">
				<pose>0 ${-room_length/2} ${wall_height/2} 0 0 0</pose>
        <collision name="collision">
          <geometry>
            <box>
              <size> ${room_width} ${wall_thickness} ${wall_height}</size>
            </box>
          </geometry>
        </collision>
        <visual name="visual">
          <cast_shadows>true</cast_shadows>
          <geometry>
            <box>
              <size> ${room_width} ${wall_thickness} ${wall_height}</size>
            </box>
          </geometry>
          <material>
						<ambient>${wall_color}</ambient>
          </material>
        </visual>
      </link>
    </model>
<xacro:macro name="draw_cylinder" params="x y name">
    <model name="${name}">
      <static>true</static>
      <link name="${name}_link">
				<pose>${x} ${y} ${wall_height/2} 0 0 0</pose>
        <collision name="collision">
          <geometry>
            <cylinder>
							<radius>0.25</radius>
							<length>${wall_height}</length>
            </cylinder>
          </geometry>
        </collision>
        <visual name="visual">
          <cast_shadows>true</cast_shadows>
          <geometry>
            <cylinder>
							<radius>0.25</radius>
							<length>${wall_height}</length>
            </cylinder>
          </geometry>
          <material>
						<ambient>${cylinder_color}</ambient>
          </material>
        </visual>
      </link>
    </model>
</xacro:macro>
<xacro:draw_cylinder name="two" x="${room_width/4}" y="${room_length/4}"/>
<xacro:draw_cylinder name="three" x="${-room_width/4}" y="${room_length/4}"/>
<xacro:draw_cylinder name="four"  x="${-room_width/4}" y="${-room_length/4}"/>
<xacro:draw_cylinder name="five"  x="${room_width/4}" y="${-room_length/4}"/>
<xacro:macro name="draw_box" params="x y name length width height">
    <model name="${name}">
      <static>true</static>
      <link name="${name}_link">
				<pose>${x} ${y} ${height/2} 0 0 0</pose>
        <collision name="collision">
          <geometry>
            <box>
							<size>${width} ${length} ${height}</size>
            </box>
          </geometry>
        </collision>
        <visual name="visual">
          <cast_shadows>true</cast_shadows>
          <geometry>
            <box>
							<size>${width} ${length} ${height}</size>
            </box>
          </geometry>
          <material>
						<ambient>${box_color}</ambient>
          </material>
        </visual>
      </link>
    </model>
</xacro:macro>
<xacro:draw_box name="box1"  x="${-room_width/8}" y="${-room_length/8}"
	length="0.5" width="0.5" height="1"/>
<xacro:draw_box name="box2"  x="${room_width/8}" y="${room_length/8}"
	length="0.5" width="0.5" height="1"/>
  </world>
</sdf>
